# Use the jupyter/datascience-notebook image as the base image
FROM jupyter/datascience-notebook:latest

# Installez les dépendances Python spécifiées dans le fichier requirements.txt
RUN pip install -r requirements.txt

# Expose the Jupyter notebook port
EXPOSE 8888
